name: Sync Repository

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sync.yml'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push changes to second repository
        env:
          SECOND_REPO_TOKEN: ${{ secrets.SECOND_REPO_PAT }}
        run: |
          git config --global user.email "webteamencircle@gmail.com"
          git config --global user.name "WebTeamET"

          git remote add second_repo https://AbhiDET:${SECOND_REPO_TOKEN}@github.com/AbhiDET/github-actions-sync-repo.git

          git push --force second_repo main
          git push --tags second_repo
