name: Sync Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push changes to second repository
        env:
          SECOND_REPO_PAT: ${{ secrets.SECOND_REPO_PAT }}
        run: |
          git config --global user.email "webteamencircle@gmail.com"
          git config --global user.name "WebTeamET"

          # Add the second repo as a remote
          git remote add second_repo https://AbhiDET:${SECOND_REPO_PAT}@github.com/AbhiDET/github-actions-sync-repo.git

          # Push all branches and tags
          git push --mirror second_repo
